-- MySQL Script generated by MySQL Workbench
-- Tue Nov 27 16:25:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema servicioTecnico_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema servicioTecnico_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `servicioTecnico_db` DEFAULT CHARACTER SET utf8 ;
USE `servicioTecnico_db` ;

-- -----------------------------------------------------
-- Table `servicioTecnico_db`.`TipoEquipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicioTecnico_db`.`TipoEquipo` (
  `idTipoEquipo` INT NOT NULL AUTO_INCREMENT,
  `tipo_equipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoEquipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicioTecnico_db`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicioTecnico_db`.`Personal` (
  `rut_personal` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `ap_pat` VARCHAR(45) NOT NULL,
  `ap_mat` VARCHAR(45) NOT NULL,
  `telefono` INT NULL,
  `fecha_contrato` DATE NULL,
  PRIMARY KEY (`rut_personal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicioTecnico_db`.`Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicioTecnico_db`.`Equipo` (
  `idEquipo` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `tipoEquipo` INT NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `fecha_salida` DATE NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `rut_encargado` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `rut_cliente` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idEquipo`),
  INDEX `FK_Equipo_Tipo_idx` (`tipoEquipo` ASC),
  INDEX `FK_Equipo_Personal_idx` (`rut_encargado` ASC),
  CONSTRAINT `FK_Equipo_Tipo`
    FOREIGN KEY (`tipoEquipo`)
    REFERENCES `servicioTecnico_db`.`TipoEquipo` (`idTipoEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Equipo_Personal`
    FOREIGN KEY (`rut_encargado`)
    REFERENCES `servicioTecnico_db`.`Personal` (`rut_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicioTecnico_db`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicioTecnico_db`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;

USE `servicioTecnico_db`;

DELIMITER $$
USE `servicioTecnico_db`$$
CREATE DEFINER = CURRENT_USER TRIGGER `servicioTecnico_db`.`Personal_AFTER_INSERT` AFTER INSERT ON `Personal` FOR EACH ROW
BEGIN
	INSERT INTO USUARIO(USERNAME, PASSWORD) VALUES(NEW.RUT_PERSONAL, NEW.RUT_PERSONAL);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `servicioTecnico_db`.`TipoEquipo`
-- -----------------------------------------------------
START TRANSACTION;
USE `servicioTecnico_db`;
INSERT INTO `servicioTecnico_db`.`TipoEquipo` (`idTipoEquipo`, `tipo_equipo`) VALUES (1, 'PC');
INSERT INTO `servicioTecnico_db`.`TipoEquipo` (`idTipoEquipo`, `tipo_equipo`) VALUES (2, 'Notebook');
INSERT INTO `servicioTecnico_db`.`TipoEquipo` (`idTipoEquipo`, `tipo_equipo`) VALUES (3, 'All in One');
INSERT INTO `servicioTecnico_db`.`TipoEquipo` (`idTipoEquipo`, `tipo_equipo`) VALUES (4, 'Smartphone');
INSERT INTO `servicioTecnico_db`.`TipoEquipo` (`idTipoEquipo`, `tipo_equipo`) VALUES (5, 'Netbook');

COMMIT;


-- -----------------------------------------------------
-- Data for table `servicioTecnico_db`.`Personal`
-- -----------------------------------------------------
START TRANSACTION;
USE `servicioTecnico_db`;
INSERT INTO `servicioTecnico_db`.`Personal` (`rut_personal`, `nombre`, `ap_pat`, `ap_mat`, `telefono`, `fecha_contrato`) VALUES (19128620, 'Jacob', 'Olivares', 'Espinoza', 968038777, '10-10-2018');
INSERT INTO `servicioTecnico_db`.`Personal` (`rut_personal`, `nombre`, `ap_pat`, `ap_mat`, `telefono`, `fecha_contrato`) VALUES (19209255, 'Esteban', 'Miranda', 'Ahumada', 973854193, '27-11-2018');

COMMIT;


-- -----------------------------------------------------
-- Data for table `servicioTecnico_db`.`Equipo`
-- -----------------------------------------------------
START TRANSACTION;
USE `servicioTecnico_db`;
INSERT INTO `servicioTecnico_db`.`Equipo` (`idEquipo`, `marca`, `modelo`, `tipoEquipo`, `fecha_ingreso`, `fecha_salida`, `descripcion`, `rut_encargado`, `estado`, `rut_cliente`) VALUES (1, 'Samsung', 'R410', 1, '2011-11-04', '2011-11-05', 'ASDASD', 19128620, 'EN TALLER', '19128620-0');

COMMIT;


-- -----------------------------------------------------
-- Data for table `servicioTecnico_db`.`Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `servicioTecnico_db`;
INSERT INTO `servicioTecnico_db`.`Usuario` (`idUsuario`, `username`, `password`) VALUES (1, '19128620', '19128620');
INSERT INTO `servicioTecnico_db`.`Usuario` (`idUsuario`, `username`, `password`) VALUES (2, '19209255', '19209255');

COMMIT;

